#ifndef GUARD_CONSTANTS_WAITING_H
#define GUARD_CONSTANTS_WAITING_H

// Choices
#define WAIT_TILL_MORNING 10
#define WAIT_TILL_DAY 20
#define WAIT_TILL_EVENING 30
#define WAIT_TILL_NIGHT 40

#endif // GUARD_CONSTANTS_WAITING_H
